chore(l10n): add initial ftl from new settings
mozilla/fxa-content-server-l10n pull request #466
Opened 2021-02-04 18:24 UTC by chenba

This commit add the initial set of strings from FxA's new settings frontend.

2021-02-04 22:04 UTC, peiying2 requested changes
Please check the initial review comments. I will go over the .ftl syntax and comment if necessary.

2021-02-04 22:04 UTC, peiying2 commented on locale/templates/settings.ftl
> +  if it's not in your email or spam.
`your email or spam` probably needs to be reworded. Maybe `your inbox or spam folder`?

2021-02-05 16:02 UTC, peiying2 commented on locale/templates/settings.ftl
> +  codes in a safe place—you’ll need them to access your account if you don’t
Add space before and after `—` em dash.

2021-02-05 16:03 UTC, peiying2 commented on locale/templates/settings.ftl
> +se-content-note = Note: a secondary email won't restore your information—you'll
Add space before and after `—` em dash

2021-02-05 18:20 UTC, peiying2 commented on locale/templates/settings.ftl
> +cs-logged-out = Logged out of { $service }.
There needs to be a reference of the variable at the beginning of this block, as seen in the example here: https://firefox-source-docs.mozilla.org/l10n/fluent/review.html#comments

2021-02-05 19:15 UTC, chenba commented
@peiying2 Thank you so much for the feedback.  I'll mark each comment as resolved as I fix them in the FxA repo.

2021-02-05 21:56 UTC, chenba commented on locale/templates/settings.ftl
> +mozilla-vpn = Mozilla VPN
I can move them.

They are used in the delete account steps.  It looks like this:
![image](https://user-images.githubusercontent.com/198055/107093371-bd2f9900-67ca-11eb-84bb-90834d36ed0b.png)

2021-02-05 22:07 UTC, peiying2 commented on locale/templates/settings.ftl
> +mozilla-vpn = Mozilla VPN
Ideally, you have a separate file called "brands.ftl" so you can keep adding there if need be and can update the list (addition or removal). Or you put them all at the top of the file, and reference the name later in the file.

2021-02-05 22:38 UTC, chenba commented on locale/templates/settings.ftl
> + .label = Any may lose saved information and features within { -mozilla } products
Appears to be a typo.  It should've been 'You may lose...".

2021-02-05 23:06 UTC, chenba commented
I pushed another commit with the changes based on the feedback for easier re-review.  I can squash into a single commit before merging.  Thanks!

2021-02-05 23:16 UTC, chenba commented on locale/templates/settings.ftl
> +mozilla-vpn = Mozilla VPN
Sorry, I didn't see this message prior to pushing my latest commit.

For clarification, is having the "brands.ftl" file for our (FxA engr) benefit, or the localizers?  This settings.ftl is actually generated from smaller ftl files in the FxA repo.  But if it helps localizers to have a "brands.ftl", we definitely can do that

2021-02-05 23:31 UTC, peiying2 commented on locale/templates/settings.ftl
> +mozilla-vpn = Mozilla VPN
It's good practice to have a separate one so it's easy to address brand related terms. Technically, brands are left untranslated, product and feature names are not translated for the most part with a few exception (Accounts in FxA, Sync). This file also allows it to grow in the future when we have more products to add. It's also easy to reference to if a product name is not coded as a placeable. Firefox and Mozilla.org have a brands.ftl each. You can keep the PR as is for now. Wil and l10n team are going to have a meeting on Monday regarding how to manage this release.

2021-02-08 18:35 UTC, peiying2 requested changes
I reverted the comment on Sync after checking with team. I will get back to you on any comment on the technical Fluent related review by tomorrow morning.

FYI, had a meeting with Wil on what to do with the PR. The suggested changes are still valid, but we may not roll out to l10n.

2021-02-08 18:35 UTC, peiying2 commented on locale/templates/settings.ftl
> +-sync = Sync
Apologize for asking you to revert back to your original setup. Marketing's suggestion is to leave this feature name out.

2021-02-08 18:35 UTC, peiying2 commented on locale/templates/settings.ftl
> +# Note: the company name, Mozilla, is not translated.
If we call out the names that shouldn't be translated, let's include Firefox as well.

2021-02-12 00:22 UTC, peiying2 reviewed
@flodolo please go review the PR. Additional questions I have:

- Usages of ## and # 
- Line space after ## (there is one line space) or # (no line space)
- Section break - without the ## or #, should there be spaces between section.  
- Which one, # or ## would a localizer see in Pontoon if immediately followed by IDed strings. The same comment is shown in every string within a block (no line space)?

2021-02-12 00:22 UTC, peiying2 commented on locale/templates/settings.ftl
> +  account password in your account settings. You should also change any other
Include `account` in { -firefox-account }

2021-02-12 08:02 UTC, flodolo requested changes

2021-02-12 08:02 UTC, flodolo commented on locale/templates/settings.ftl
> +# Note: include the placeholder '{ $email }' without translation. It will be replaced with the user's email address.
I'd replace this comment with just the standard format for the variable.

2021-02-12 17:11 UTC, chenba commented on locale/templates/settings.ftl
> + .label = Any paid subscriptions you have will be cancelled
TIL `cancelled` is Canadian!  (Which was why it always looked weird to me.)

2021-02-12 17:13 UTC, chenba commented
Thanks for the great feedback, @flodolo.  I'll mark each comment resolved as I make the suggested change in the FxA repo.

2021-02-12 20:15 UTC, chenba commented on locale/templates/settings.ftl
> +  or <br /><linkExternal>send a download link to your device.</linkExternal>
I think the expectation was that Fluent can auto handle the indentation correctly (per https://www.projectfluent.org/fluent/guide/multiline.html), but that was an awkward spot to have a line break.  I'll update it so it's all one line.

2021-02-12 20:19 UTC, chenba commented on locale/templates/settings.ftl
> +  or <br /><linkExternal>send a download link to your device.</linkExternal>
Oh I think I misunderstood.  You mean the space that precedes the br tag?  I don't think it'll be a problem.

2021-02-12 21:59 UTC, chenba commented on locale/templates/settings.ftl
> +cs-disconnect-sync-reason = What's the main reason for disconnecting this
I'm certainly not aware of such rules.  (I've been on the FxA team for a little over 1.5 years.)  I'll update the `'` and `""`  to `’` and `“”`.

2021-02-16 18:49 UTC, 6a68 commented on locale/templates/settings.ftl
> +avatar-page-add-photo = Add Photo
(I'm taking over the remaining items here, marking comments as resolved as they are addressed in the branch.) These strings are only used in two spots each; the variable is used to minimize the amount of duplicated work we ask of the localizers. I'll update the remove-photo string to use a variable for the title attribute as well.

2021-02-16 21:30 UTC, peiying2 commented
Thanks to flod for all the review comments (I am taking notes too for future reviews). I am not clear what the team's plan is for this PR. From the discussion we had with Wil, if the new Setting were to go live per the original launch plan, and migration of existing translated strings from .po to .ftl is not doable, then this PR needs to be configured so the new strings won't land in Pontoon.

2021-02-16 22:09 UTC, 6a68 commented
> I am not clear what the team's plan is for this PR

Hey @peiying2, Barry is working on another project this week, so I'm taking over this work. We are planning to migrate the existing translations from the .po files to the .ftl files (this is tracked by https://github.com/mozilla/fxa/issues/7459). I'm also going to land fixes in FxA based on the review comments here (in https://github.com/mozilla/fxa/pull/7540).

We can plan to close this for now, and I can open a new PR that includes the migrated existing strings, once I've pulled them over using the new format. Does that sound good? If so, feel free to just close this PR.

2021-02-18 21:06 UTC, 6a68 commented
Update: we're going to just land this file as-is. It turns out there aren't many reused strings. Reopening.

2021-02-18 21:30 UTC, 6a68 commented
@flodolo Hi, I can't seem to re-request a review from you using the github interface, but this PR has been updated, if you have bandwidth to take another look.

2021-02-18 22:43 UTC, peiying2 requested changes
Thanks for the fix. A few more missed.

Flod is off on Friday.

2021-02-18 22:43 UTC, peiying2 commented on locale/templates/settings.ftl
> +-product-firefox-accounts = Firefox Accounts
Both `Accounts` and `Account` are localizable.

2021-02-18 22:43 UTC, peiying2 commented on locale/templates/settings.ftl
> +  keep your information safe, you should change your { -product-firefox-account } password
should be plural `{ -product-firefox-accounts }`

2021-02-18 22:43 UTC, peiying2 commented on locale/templates/settings.ftl
> +verify-secondary-email-please-enter-code = Please enter the verification code that was sent to <strong>{$email}</strong> within 5 minutes.
space before and after variable? `<strong>{ $email }</strong>`

2021-02-18 22:43 UTC, peiying2 commented on locale/templates/settings.ftl
> +# This string is instruction in a form.
Add `an` in `This string is an instruction...`

2021-02-18 22:43 UTC, peiying2 commented on locale/templates/settings.ftl
> +delete-account-confirm-title = You’ve connected your { -product-firefox-account } to { -brand-mozilla } products that keep you secure and productive on the web:
Plural accounts `{ -product-firefox-accounts }`

2021-02-19 00:31 UTC, clouserw commented
@peiying2 Jared pushed an updated patch for review

2021-02-19 00:53 UTC, peiying2 approved these changes
Looks good to me. If we have any issues, I will report back to get it fixed.

2021-02-19 00:54 UTC, merged