merge strings for train 36061
mozilla/fxa-content-server-l10n pull request #541
Opened 2021-12-16 22:08 UTC by bug-mirror

2021-12-16 22:28 UTC, peiying2 commented on locale/templates/auth.ftl
> +subscriptionsPaymentProviderCancelled-subject = Payment information update required for Mozilla subscriptions
Mozilla is a brand

2021-12-16 22:31 UTC, peiying2 commented on locale/templates/auth.ftl
> +-paypal = PayPal
should consider change brand names to `-brand-paypal` to differentiate brand/product names from others.

2021-12-16 22:50 UTC, peiying2 requested changes
Other than what's called on at string level, one general comment is on the `string level` comment - lots of repetitions. Should consider "section comment" as discussed here in this [doc](https://github.com/mozilla-l10n/documentation/blob/main/src/localization/dev_best_practices.md#fluent-files) . One example:  # `$productNameNew (String) - The name of the new subscribed product, e.g. Mozilla VPN`

2021-12-17 15:54 UTC, xlisachan commented
Thanks for feedback, @peiying2! We'll make the fix for the Mozilla and PayPal brand names now.

Regarding the section comment, can you confirm that it should look as follows?
`## Common email variables`
`# $productNameNew (String) - The name of the new subscribed product, e.g. Mozilla VPN`

Also, would it be preferable to have one section comment of all email variables within `locale/templates/auth.ftl` (where we will revise the PayPal brand name), or have each email have its own section comment of only the variables used in its `en.ftl`?

Please let us know when you have a moment. Thank you!

2021-12-17 16:35 UTC, peiying2 commented
> Thanks for feedback, @peiying2! We'll make the fix for the Mozilla and PayPal brand names now.
> 
> Regarding the section comment, can you confirm that it should look as follows? `## Common email variables` `# $productNameNew (String) - The name of the new subscribed product, e.g. Mozilla VPN`
> 
> Also, would it be preferable to have one section comment of all email variables within `locale/templates/auth.ftl` (where we will revise the PayPal brand name), or have each email have its own section comment of only the variables used in its `en.ftl`?
> 
> Please let us know when you have a moment. Thank you!

Thank you for the fixes. Let's leave the "common variables" as they are. They are not a blocker for merging this PR. We can discuss how to best address common variables at section (feature) level.

2021-12-17 16:53 UTC, LZoog commented
@peiying2 I pushed an update to bug-mirror's PR with Lisa's fixes. 🙂

2021-12-20 17:12 UTC, merged